### ISSUE TITLE
Support “Open in MATLAB Online” workflow

### ISSUE THREAD

**Issue by theavuik** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#10]
Support “Open in MATLAB Online” workflow (https://www.mathworks.com/products/matlab-online/git.html) , including a gateway
live script orienting new users to available examples (via relative links)

**Comment by vijayiyer05** [comment]
Breaking this down, this involves:
- Identifying which examples can practically run in MATLAB Online, and updating README accordingly (add run links for those that can & removing them for others)
- Adding the Open in MATLAB Online badge (link above)
- Replacing the "Find/add folder" section either using sample data or remote data access for larger data/models (#9)

Note: README updates can be made independently from the code release points

**Comment by theavuik** [comment]
Note: when removing the link for the 55.6 GB example, add an asterisk with explanation.

The view links should be transferred to file exchange links.

**Comment by jbentvelsen** [comment]
@vijayiyer05
> - Replacing the "Find/add folder" section either using sample data or remote data access for larger data/models
Can you elaborate a bit on this point? Is it simply referring to issue #9, regarding automatically downloading (large) model files, if not available in the repo? That work in that issue however does not replace the "Find/add folder" section.

**Comment by vijayiyer05** [comment]
@jbentvelsen Thanks for this good question. The 'bigger' idea behind #9 was to make the data aspects as automatic as possible. Where it's external storage, that meant to auto download. For local sample data, I think that would mean specifying full relative paths (relative from the example location). 

I can see now that the find/add folder is partly about code aspects, not just data aspects. So let's defer removing that as you say.

If at the end of this issue, that step is not germane to any data aspects, I'd say we can declare victory for now! We can tackle relative code locations at a later point & ultimately remove that awkward step. I'll create a new issue for this shortly.

**Comment by jbentvelsen** [comment]
Indeed, the script still depends on adding the root folder of the repository to path. Currently, a pop-up shows up to select this folder. I guess we can remove that, and use full relative paths to the files (instead of only the filenames, relying on those files being in the path).

**Comment by vijayiyer05** [comment]
If you see a very quick path to removing that pop-up step, it's worth it to do now. 

If not, it would be good to briefly summarize the remaining dependencies here, which can become part of the new issue.

**Comment by jbentvelsen** [comment]
Let's make it part of the next issue:
- Remove the pop-up for adding the cwd to the path. In the livescripts plain filenames need to be replaced by relative paths to the files.
