### ISSUE TITLE
Creation of release 0.6

### ISSUE THREAD

**Issue by theavuik** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#11]
Creation of a release on the Public Hosting Site incorporating issues https://github.com/INCF/DeepInterpolation-MATLAB/issues/9 and https://github.com/INCF/DeepInterpolation-MATLAB/issues/10,
including succinct release notes

**Comment by vijayiyer05** [comment]
Suggest to number this 0.6, following the planned first release (0.5) recently discussed that captures Manisha's initial work. Having the first numbered release correspond to the past work helps to memorialize it properly. 

Am reluctant to get to 1.0 until there's been a few pilot users.

**Comment by stevevanhooser** [comment]
This is now complete. Closing it now.
