### ISSUE TITLE
Add new live script examples showing inference on a public dataset

### ISSUE THREAD

**Issue by theavuik** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#14]
Update code and add new live script examples showing inference on a public dataset
from the DANDI archive (https://dandiarchive.org/), while:
• using remote data access via Amazon Web Services S3 bucket technology
• verifying example runs on the DANDIHub science gateway
(https://hub.dandiarchive.org/hub)

**Comment by vijayiyer05** [comment]
For the public dataset, a/the best known option on DandiHub is Dandiset [000037](https://dandiarchive.org/dandiset/000037/0.230426.0054). 

This is one of the (relatively) few Dandi Archive datasets with raw data.

**Comment by vijayiyer05** [comment]
Hi @jbentvelsen, downloads are still needed on Dandi, as shown in the example. The key advantage of the Dandi compute environment is there is ample disk space.
