### ISSUE TITLE
Creation of release 0.7

### ISSUE THREAD

**Issue by theavuik** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#16]
Creation of a release on the Public Hosting Site incorporating issues https://github.com/INCF/DeepInterpolation-MATLAB/issues/12, https://github.com/INCF/DeepInterpolation-MATLAB/issues/13, https://github.com/INCF/DeepInterpolation-MATLAB/issues/14, and https://github.com/INCF/DeepInterpolation-MATLAB/issues/15,
including succinct release notes

**Comment by stevevanhooser** [comment]
@theavuik I will merge PR 34 after testing and then post the new version. Thanks!

**Comment by stevevanhooser** [comment]
Version 0.7.0 was released yesterday
