### ISSUE TITLE
Add fMRI, datastore examples to README.md

### ISSUE THREAD

**Issue by stevewds** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#33]
Hi - 

Can you all please add these to the README.md with View and Run (matlab online) links please?

(fMRI and datastore)

Then I think we are ready for v0.6.0

Thanks!

**Comment by jbentvelsen** [comment]
I will add the links (and a short descriptions) for the datastore as part of the PR #34.

**Comment by stevevanhooser** [comment]
I added this for Society for Neuroscience meeting, so it's done
