### ISSUE TITLE
importKerasLayers deprecation

### ISSUE THREAD

**Issue by stevevanhooser** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#43]
The following Livescripts use importKerasLayers, which produces a warning ("Warning: 'importKerasLayers' is not recommended and will be removed in a future release. To import TensorFlow-Keras models, save using the SavedModel format and use importNetworkFromTensorFlow function.")

tiny_ephys_inference.mlx
tiny_ephys_training.mlx
tiny_ophys_inference.mlx

**Comment by stevevanhooser** [comment]
@tkuenzmw  Any thoughts on this? Any idea who might be the right person to address this issue? 

Thanks
Steve

**Comment by tkuenzmw** [comment]
> @tkuenzmw Any thoughts on this? Any idea who might be the right person to address this issue?
> 
> Thanks Steve

I have to admit I have no idea, but I will find out!

**Comment by stevevanhooser** [comment]
closed by PR69
