### ISSUE TITLE
Target center volume for fMRI 

### ISSUE THREAD

**Issue by jeromelecoq** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#47]
Thanks SO MUCH for working on this repo. We are definitely appreciative of all the work. 

I am reviewing the inference code for fMRI and I think there are a few key differences with how the network was trained in the original paper. The confusion is understandable. 

See here : https://github.com/AllenInstitute/deepinterpolation/blob/25333467409a9359b076f392d01a61bffcb8ed4d/deepinterpolation/generator_collection.py#L300

I am comparing to this code here : 
https://viewer.mathworks.com/?viewer=live_code&url=https%3A%2F%2Fwww.mathworks.com%2Fmatlabcentral%2Fmlc-downloads%2Fdownloads%2F84c22101-bffc-435a-910c-b0c7dcd5b386%2F29e7e92d-4639-4178-8e19-739580981e60%2Ffiles%2Fexamples%2Ftiny_fMRI_inference.mlx&embed=web

The fMRI was done slightly differently than ophys and ephys given the specificity of this data. 
Obviously there are many ways to slice this cake but for the sake of consistency it is important. 

Here is what I noted : 
- The input volume omission was blanked to zeros only inside the omitted volume not the ENTIRE volume at time t. 
The risk is that the network is missing valuable input information to predict the fMRI volume at time t.

- The global normalization were calculated on the inside of the brain to avoid the impact of black pixels around which are a little more predominant in fMRI than ophys and ephys.

**Comment by jeromelecoq** [comment]
It might be worth doing a numerical comparison with python also. I do not know what to except here.

**Comment by tkuenzmw** [comment]
That is something I wanted to try for a while, as I have both the MATLAB and Python versions set up. I will try to get going with this and let you know.

**Comment by jeromelecoq** [comment]
That would be great! I guess they should be within some sort of numerical tolerance. fMRI is likely more sensitive given the smaller amplitude of the signal change.

**Comment by stevevanhooser** [comment]
@tkuenzmw What's the status of this issue? Thanks

**Comment by stevevanhooser** [comment]
It's my understanding that PR#76 closes this issue.
