### ISSUE TITLE
custom datastore workflow for DeepInterpolation-MATLAB

### ISSUE THREAD

**Issue by tkuenzmw** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#6]
Upon Vijays suggestion I pushed my branch of Deepinterpolation-MATLAB. This contains an example of a custom datastore that can be used to train the DeepInterpolation-MATLAB model with "unlimited" number of frames (my scientific partners report using >4000 frames for training without finding issues...). I also added "stand-alone" training and inference functions that can be run as batch jobs e.g. on a cluster. A workflow-demo .mlx file explain the use.

--> all this does not have to be merged as is into the project, this is meant as an example how to expand the DeepInterpolation-MATLAB idea tested by actual scientific beta users (at the RWTH Aachen University and the MPI for the Neurobiology of Behavior in Bonn)

**Comment by vijayiyer05** [comment]
As discussed:

- it may make sense to make a fresh example proving out the new datastore 
- it may make sense to have this new example use a Dandiset & be tested/run on DandiHub (caveat: CPU only for now)
- this [example ](https://github.com/aranega/example-live-scripts/blob/main/000207/MarielleDarwin-2023/Cognitive-Boundaries/startup/startup.m )shows how to access Dandisets on DandiHub

Reach out to me with any Dandi/DandiHub questions!
