### ISSUE TITLE
Neuropixels example network requires data transform due to data from Neuropixels Phase 3a

### ISSUE THREAD

**Issue by stevevanhooser** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#77]
The current `tiny_ephys_inferrence.mlx` example (as of 2024-12-20) uses a trained network ([2020_02_29_15_28_unet_single_ephys_1024_mean_squared_error-1050.zip](https://github.com/MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB/blob/main/pretrainedModels/2020_02_29_15_28_unet_single_ephys_1024_mean_squared_error-1050.zip)) that accepts input that is 384x2x60. It also reads in data from a single Neuropixels probe that has data that is NSAMPLES x 192 x 2 (` `). 

At first, there seems to be a mismatch between the trained network and the Neuropixels data. But it has to do with the geometry of the Phase 3a probe used in these experiments.

The Phase 3a probe has a checkerboard layout. On one column (say the left), the first electrode pad occupies a certain position. To its right, there is no electrode immediately adjacent but instead it is offset lower down on the probe. The electrode array continues in this pattern. (See https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/77332482/Neuropixels+Probes but I cannot find a good image of it at this time.)

The authors apparently transformed the data so that the transformed data reflects the physical geometry of the electrode. At the "top left", there is an electrode, but the data in the matrix at both the positions to the right and lower are set to 0, reflecting the absence of an electrode at that location. Therefore, if we take the ephys data as coming from individual channels numbered in 0.5 number increments, the data samples look like:

```
    1.0000    1.5000
    2.0000    2.5000
    3.0000    3.5000
...
  189.0000  189.5000
  190.0000  190.5000
  191.0000  191.5000
```

where as each frame of the transformed data that is fed to the interpolation is

```
    1.0000         0
         0    1.5000
    2.0000         0
         0    2.5000
    3.0000         0
         0    3.5000
...
  190.0000         0
         0  190.5000
  191.0000         0
         0  191.5000
  192.0000         0
         0  192.5000
```
An examination of the Python distribution (https://github.com/AllenInstitute/deepinterpolation) shows that its example [example_tiny_ephys_inference.py](https://github.com/AllenInstitute/deepinterpolation/blob/master/examples/example_tiny_ephys_inference.py) does exactly the same thing.

I think that in the current version of the tutorial, this is pretty unclear to the reader. I will add a transform and untransform function and add a line of description in the metadata.

**Comment by vijayiyer05** [comment]
Great to see progress in better understanding the transformation steps, which I had found confusing. 
I'll aim to take a look sometime (TBD) over the next couple of holiday weeks.
